const express = require("express");
const cors = require("cors");
const app = express();
const patientrouter = require("./hospital/patient/patient");
const DoctorRouter = require("./hospital/doctor/doctor");
const AppointmentRouter = require("./hospital/appointment/appointment");
const PaymentRouter = require("./hospital/payment/payment");
const Roomrouter = require("./hospital/Room/room");
const PatientUserRouter = require("./hospital/userSignup/patientusers/patientusers");
const DoctorUserrouter = require("./hospital/userSignup/doctorusers/doctorusers");
const patientauthRouter = require("./hospital/logauth/patientuser/patientlogauth");
const doctorauthRouter = require("./hospital/logauth/doctoruser/doctorlogauth");
const adminauthRouter = require("./hospital/logauth/admin/admin");
const DoctorSpecialistData = require("./hospital/Specialistdata/Specialist");
const Departmentlist = require("./hospital/Department/department");
const userpasswordreset = require("./hospital/forget/password");
app.use(cors());
app.use(express.json());
app.use(express.Router());
app.use("/patient", patientrouter);
app.use("/Doctor", DoctorRouter);
app.use("/Appointment", AppointmentRouter);
app.use("/payment", PaymentRouter);
app.use("/room", Roomrouter);
app.use("/user/signup/patient", PatientUserRouter);
app.use("/user/signup/doctor", DoctorUserrouter);
app.use("/patientauth", patientauthRouter);
app.use("/doctorauth", doctorauthRouter);
app.use("/AdminLogin", adminauthRouter);
app.use("/Doctor/Speciallist/data", DoctorSpecialistData);
app.use("/hospital/departmentlist", Departmentlist);
app.use("/user", userpasswordreset);
app.listen(4000, console.log("server is runnning on 4000"));
